name: Bug Report
description: 回報一個你遇到的問題
title: "[Bug] "
labels: [bug]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        請填寫以下資訊以幫助我們了解你的問題。

  - type: input
    id: environment
    attributes:
      label: 運行環境
      description: 請說明你的作業系統、瀏覽器或其他相關資訊
      placeholder: e.g., Windows 11 + Chrome 123

  - type: textarea
    id: steps
    attributes:
      label: 重現步驟
      description: 請詳述重現問題的步驟
      placeholder: |
        1. 打開網站
        2. 點選登入
        3. 發生錯誤
      value: ""

  - type: textarea
    id: expected
    attributes:
      label: 預期結果
      description: 請說明你原本預期的行為
      value: ""

  - type: textarea
    id: actual
    attributes:
      label: 實際結果
      description: 實際上發生了什麼？
      value: ""